name: Build, Test, Lint, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install
          npm install --save-dev @babel/plugin-proposal-private-property-in-object

      - name: Lint Code
        run: |
          npm run lint 2>&1 | tee -a build_log.txt

      - name: Run Tests
        run: |
          npm test 2>&1 | tee -a build_log.txt

      - name: Build Project
        run: |
          npm run build 2>&1 | tee -a build_log.txt

      - name: Deploy to HostGator
        if: success()
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 108.167.151.65 >> ~/.ssh/known_hosts
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o IdentitiesOnly=yes" --delete build/ hiper170@108.167.151.65:/home/hiper170/public_html/build
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o IdentitiesOnly=yes" --delete public/ hiper170@108.167.151.65:/home/hiper170/public_html/public

      - name: Notify Discord on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "Build and deploy successful!"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord on Failure
        if: failure()
        run: |
          echo "Build and deploy failed." > error_log.txt
          echo "\`\`\`" >> error_log.txt
          cat build_log.txt >> error_log.txt
          echo "\`\`\`" >> error_log.txt
          curl -F "file=@error_log.txt" -F "payload_json={\"content\": \"Build and deploy failed. See attached log for details.\"}" ${{ secrets.DISCORD_ERROR_WEBHOOK_URL }}
